services:
  kb-ui:
    container_name: kb-ui
    image: ghcr.io/yarozers/kb-ui:latest
    ports:
      - 4200:80
    networks:
      - kb

networks:
  kb:
    name: kb  # Явное указание имени сети
    external: true
    driver: bridge

volumes:
  postgres:
    driver: local
#    строка для запуска workflow111

