version: '3.8'

services:
  postgres:
    container_name: postgres-sql-kb
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: keycloak
    volumes:
      - postgres:/var/lib/postgresql/data  # Обратите внимание на исправление пути к данным
    ports:
      - 5430:5432
    networks:
      - kb
    restart: unless-stopped

networks:
  kb:
    name: kb  # Явное указание имени сети
    external: true
    driver: bridge

volumes:
  postgres:
    driver: local
