version: '3.8'

services:
  keycloak:
    container_name: keycloak-kb
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - 9999:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - kb
    command: ["start-dev"]

networks:
  kb:
    name: kb
    driver: bridge
