name: KB Frontend Pipeline

on:
  push:
    branches:
      - master
    paths:
      - ./**
      - docker/frontend/**
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml

jobs:
  build-image:
    name: Build FE Docker image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract project version
        id: extract_version
        run: |
          echo "Extracting project version..."
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build & Push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/yarozers/kb-ui:${{ steps.extract_version.outputs.VERSION }},ghcr.io/yarozers/kb-ui:latest
          build-args: |
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
            # Add more build arguments if needed

  deploy:
    name: Deploy Frontend
    runs-on: self-hosted
    needs: [ build-image ]
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Create deployment folder
        run: |
          echo "Creating deployment folder on server..."
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p kb-ui" || (echo "Error during SSH command" && exit 1)

      - name: Copy docker-compose file
        run: |
          echo "Copying docker-compose file to server..."
          scp -P ${{ secrets.VPS_PORT }} docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:kb-ui/docker-compose.yml || (echo "Error during SCP command" && exit 1)

      - name: Set ENV variables and deploy
        run: |
          echo "Setting environment variables and deploying..."
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd kb-ui
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF
